# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=150)),
                ('tags', models.CharField(max_length=100)),
                ('vanskelig', models.FloatField()),
                ('info', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Studie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('rangering', models.FloatField()),
                ('beskrivelse', models.CharField(max_length=1000)),
                ('url', models.URLField()),
            ],
        ),
    ]
