# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentportalen', '0004_vurdering'),
    ]

    operations = [
        migrations.AddField(
            model_name='vurdering',
            name='tittel',
            field=models.CharField(default='Tittel', max_length=200),
        ),
    ]
