# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Studentportalen', '0005_vurdering_tittel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vurdering',
            name='emne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Studentportalen.Emne'),
        ),
    ]
