# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentportalen', '0006_vurdering_emne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vurdering',
            name='arbeid',
            field=models.IntegerField(choices=[(1, 'Veldig lite'), (2, 'Lite'), (3, 'Middels'), (4, 'Mye'), (5, 'Veldig mye')], default=1),
        ),
        migrations.AlterField(
            model_name='vurdering',
            name='interesse',
            field=models.IntegerField(choices=[(1, 'Veldig lite'), (2, 'Lite'), (3, 'Middels'), (4, 'Ganske interessant'), (5, 'Veldig interessant')], default=1),
        ),
        migrations.AlterField(
            model_name='vurdering',
            name='vanskelig',
            field=models.IntegerField(choices=[(1, 'Veldig lett'), (2, 'Lett'), (3, 'Middels'), (4, 'Vanskelig'), (5, 'Veldig vanskelig')], default=1),
        ),
    ]
