# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studentportalen', '0007_auto_20171106_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='emne',
            name='antall',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vurdering',
            name='arbeid',
            field=models.IntegerField(choices=[(1, '1 - Veldig lite'), (2, '2 - Lite'), (3, '3 - Middels'), (4, '4 - Mye'), (5, '5 - Veldig mye')], default=1),
        ),
        migrations.AlterField(
            model_name='vurdering',
            name='interesse',
            field=models.IntegerField(choices=[(1, '1 - Veldig lite'), (2, '2 - Lite'), (3, '3 - Middels'), (4, '4 - Ganske interessant'), (5, '5 - Veldig interessant')], default=1),
        ),
        migrations.AlterField(
            model_name='vurdering',
            name='vanskelig',
            field=models.IntegerField(choices=[(1, '1 - Veldig lett'), (2, '2 - Lett'), (3, '3 - Middels'), (4, '4 - Vanskelig'), (5, '5 - Veldig vanskelig')], default=1),
        ),
    ]
